### ISSUE TITLE
yellow plate

### ISSUE THREAD

**Issue by AlanNewImage** [xuexingyu24/License_Plate_Detection_Pytorch#1]
Hi:
    tks for your nice work!
    Only support blue plate now?

**Comment by xuexingyu24** [comment]
The model is trained using CCPD dataset.  you need to prepare the blue plate data to extend the model  capability

**Comment by xuexingyu24** [comment]
The model is trained using CCPD dataset.  you need to prepare the blue plate data to extend the model  capability

**Comment by dl8207531** [comment]
你这个有测下安卓下的速度吗？ 你这个和我的思路很像 不过我的网络要小很多
https://blog.csdn.net/42252343

**Comment by xuexingyu24** [comment]
还没有测试

**Comment by xuexingyu24** [comment]
closed
